---
#- name: Playbook - Install cowsay    
#  connection: ssh     
#  gather_facts: yes   

#  tasks:                              
  - name: using apt to install cowsay  
    apt:                     
        name: cowsay         
        state: latest      
    become: yes         

  - name: Add a log entry
    lineinfile:
      path: ~/loggy.log
      line:  "{{ ansible_date_time.iso8601 }} - Passed Checkup"
#    line:  "{{ ansible_date_time }} - Passed Checkup"
#    line:  "{{ ansible_date_time.date }} - Passed Checkup"
      create: True

