---
- name: Playbook - Install sl    
  connection: ssh     # default is to use the connection plugin ssh.py
  gather_facts: yes   # default is yes

  tasks:                              
  - name: using apt to install sl  
    apt:                     
        name: figlet         
        state: present      
    become: yes         

